repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|vue|json|css|scss|md)$
        exclude: |
          (?x)^(
            package-lock\.json|
            \.prettierignore|
            node_modules/.*|
            dist/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: \.(js|ts|vue)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - '@vitejs/plugin-vue@^5.0.4'
          - '@vue/eslint-config-prettier@^9.0.0'
          - '@vue/eslint-config-typescript@^14.1.3'
          - '@typescript-eslint/eslint-plugin@^8.23.0'
          - '@typescript-eslint/parser@^8.23.0'
          - 'eslint@^8.57.0'
          - 'eslint-plugin-vue@^9.23.0'
          - 'eslint-plugin-vuetify@^2.4.0'
          - 'eslint-plugin-import@^2.31.0'
          - 'typescript@^5.7.2'

  - repo: local
    hooks:
      - id: vue-tsc
        name: vue-tsc type check
        entry: npx vue-tsc --noEmit
        language: node
        files: \.(ts|vue)$
        pass_filenames: false

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] frontend pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false