# Development-specific overrides
services:
  postgres:
    environment:
      POSTGRES_DB: gene_curator_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d  # Use main SQL files
      - dev_postgres_data:/var/lib/postgresql/data

  backend:
    environment:
      DATABASE_URL: postgresql://dev_user:dev_password@postgres:5432/gene_curator_dev
      ENVIRONMENT: development
      DEBUG: "true"
      LOG_LEVEL: debug
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:8001
      VITE_ENVIRONMENT: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  dev_postgres_data:
    driver: local